### ISSUE TITLE
boruta using all threads on server

### ISSUE THREAD

**Issue by nick-youngblut** [mbq/Boruta#3]
Boruta uses ranger, which itself uses all CPUs by default. It seems that there's no way to pass the number of threads to ranger through the `boruta` function. Thus, running `boruta` uses all threads on a machine, which is NOT ok for shared servers where many individuals must share the computational resources. Members of my department are running boruta on large datasets and monopolizing our server as a result. 

Is there actually a way to limit the threads that `ranger` is using within the `boruta` function? If not, can you please add this feature to `boruta`?

**Comment by mbq** [comment]
`Boruta` function passes down all unmatched arguments to the importance source wrapper, and this (usually) further to the underlying algorithm; so all you have to do it add `num.threads=X` to your `Boruta` call.

**Comment by nick-youngblut** [comment]
Thanks for letting me know! My colleagues and I must have missed that in the docs.
